base_inventario/base_inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from .views import PedidoPDF, EmpresasPDF, PerfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('productos/', include('productos.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido_pdf/', login_required(PedidoPDF.as_view()), name='pedido_pdf'),
    path('empresas_pdf/', login_required(EmpresasPDF.as_view()), name='empresas_pdf'),
    path('perfiles_pdf/', login_required(PerfilPDF.as_view()), name='perfiles_pdf'),
]

base_inventario/perfil/urls.py
from django.urls import path
from .views import RegistroUsuario, empresas_index, Usuario_ListView, proveedores_list, Listado_empresas, Crear_empresa, Editar_empresa, Eliminar_empresa, PerfilCrear, index_perfiles
from django.contrib.auth.decorators import login_required

app_name = 'perfil'
urlpatterns = [
    path('index_perfiles/', index_perfiles, name='index_perfiles'),
    path('crear', login_required(RegistroUsuario.as_view()), name='crear'),
    path('usuario_list', Usuario_ListView.as_view(), name='usuario_list'),
    path('empresas_index', empresas_index, name='empresas_index'),
    path('empresa', Crear_empresa.as_view(), name='empresa'),
    path('empresas_list', Listado_empresas.as_view(), name='empresas_list'),
    path('editar/<int:pk>/', Editar_empresa.as_view(), name='empresas_edit'),
    path('eliminar/<int:pk>/', Eliminar_empresa.as_view(), name='empresas_delete'),
    path('proveedores_crear', PerfilCrear.as_view(), name='proveedores_crear'),
    path('proveedores_list', proveedores_list, name='proveedores_list'),
]

base_inventario/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from productos.views import (
    index_productos, Listado_producto, Editar_producto, Borrar_producto,
    Listado_pedido, Editar_pedido, Borrar_producto_pedido, Listado_categorias,
    inventario_view, Crear_producto, Detalles_producto, Crear_pedido, ProductosPorCategoriaView)

from django_filters.views import FilterView
from .filters import ProductoFilter

app_name = 'productos'

urlpatterns = [
    path('index', login_required(index_productos), name='index_productos'),
    path('nuevo', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    path('pedido', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
    path('listar', login_required(Listado_producto.as_view()), name='productos_listar'),
    re_path(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
    re_path(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
    path('buscar_producto', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='producto_filtro_list.html')), name='buscar_producto'),
    re_path(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
    re_path(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
    re_path(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()), name='pedido_edit'),
    path('pedido_list', login_required(Listado_pedido.as_view()), name='pedido_list'),
    path('categorias_list', login_required(Listado_categorias.as_view()), name='categorias_list'),
    path('inventario_view', login_required(inventario_view), name='inventario_view'),
    path('buscar_producto_por_empresa', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),
    path('productos/<int:categoria_id>/', ProductosPorCategoriaView.as_view(), name='productos_por_categoria'),


]

base_inventario/productos/models.py
from django.db import models
from perfil.models import EmpresaProveedor

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Factor_empaque(models.Model):
    factor_de_empaque = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return self.factor_de_empaque

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(blank=True, null=True)
    marca = models.CharField(max_length=50)
    precio_unitario = models.DecimalField(decimal_places=2, max_digits=10000)
    inventario = models.IntegerField(default=0)
    factor_de_empaque = models.ForeignKey(Factor_empaque, null=True, on_delete=models.SET_NULL)
    fecha_compra = models.DateTimeField(auto_now_add=True)
    empresa_proveedor = models.ForeignKey(EmpresaProveedor, null=True, blank=False, on_delete=models.SET_DEFAULT, default="")
    categoria = models.ManyToManyField(Categoria, blank=True)

    def __str__(self):
        return f'{self.nombre}{self.id}'

class Pedido_mercaderia(models.Model):
    producto_a_pedir = models.OneToOneField(Producto, blank=False, on_delete=models.SET_DEFAULT, default="")
    fecha_compra = models.DateTimeField(auto_now_add=True)
    cantidad = models.IntegerField(blank=False)

    class Meta:
        verbose_name = "Pedido de Producto"
        verbose_name_plural = "Pedidos de Productos"

    def __str__(self):
        return str(self.producto_a_pedir)

base_inventario/productos/forms.py
from django import forms
from productos.models import Producto, Pedido_mercaderia

class ProductoForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-md-12'}))
    class Meta:
        model = Producto
        fields = [
            'nombre',
            'descripcion',
            'marca',
            'precio_unitario',
            'inventario',
            'factor_de_empaque',
            'empresa_proveedor',
            'categoria',
        ]
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'marca': 'Marca',
            'precio_unitario': 'Precio/unidad',
            'factor_de_empaque': 'Factor de empaque',
            'inventario': 'Inventario',
            'empresa_proveedor': 'Proveedor',
            'categoria': 'Categoría',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-group'}),
            'descripcion': forms.Textarea(attrs={'cols': 56, 'rows': 5}),
            'marca': forms.TextInput(attrs={'class': 'form-group'}),
            'precio_unitario': forms.TextInput(attrs={'class': 'form-group'}),
            'factor_de_empaque': forms.Select(attrs={'class': 'form-group'}),
            'inventario': forms.TextInput(attrs={'class': 'form-group'}),
            'empresa_proveedor': forms.Select(attrs={'class': 'form-control'}),
            'categoria': forms.CheckboxSelectMultiple(attrs={'class': 'form-check-inline'}),
        }

class Pedido_mercaderiaForm(forms.ModelForm):
    class Meta:
        model = Pedido_mercaderia
        fields = ['producto_a_pedir', 'cantidad']
        labels = {
            'producto_a_pedir': 'Elegir Mercadería',
            'cantidad': '¿Cuántos artículos desea pedir?',
        }
        widgets = {
            'producto_a_pedir': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.TextInput(attrs={'class': 'form-control'}),
        }

base_inventario/productos/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from productos.forms import ProductoForm, Pedido_mercaderiaForm
from productos.models import Producto, Pedido_mercaderia, Categoria
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import ProductoFilter
from django_filters.views import FilterView

def index_productos(request):
    return render(request, 'index_productos.html')

def inventario_view(request):
    return render(request, 'index_inventario.html')

class Listado_producto(ListView):
    ordering = ['empresa_proveedor']
    model = Producto
    template_name = 'lista_productos.html'
    paginate_by = 6

class Crear_producto(SuccessMessageMixin, CreateView):
    model = Producto
    template_name = 'productos_form.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:productos_listar')
    success_message = "Articulo almacenado correctamente"

class Editar_producto(UpdateView):
    model = Producto
    template_name = 'productos_form.html'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:productos_listar')

class Borrar_producto(DeleteView):
    model = Producto
    template_name = 'productos_delete.html'
    success_url = reverse_lazy('productos:productos_listar')

class Detalles_producto(DetailView):
    model = Producto
    queryset = Producto.objects.all()
    template_name = 'detalles_productos.html'

class Crear_pedido(CreateView):
    model = Pedido_mercaderia
    template_name = 'CRUD_pedido.html'
    form_class = Pedido_mercaderiaForm
    success_url = reverse_lazy('productos:pedido_list')

class Editar_pedido(UpdateView):
    model = Pedido_mercaderia
    template_name = 'CRUD_pedido.html'
    form_class = Pedido_mercaderiaForm
    success_url = reverse_lazy('productos:pedido_list')

class Listado_pedido(ListView):
    ordering = ['id']
    model = Pedido_mercaderia
    template_name = 'pedido_reporte.html'

class Borrar_producto_pedido(DeleteView):
    model = Pedido_mercaderia
    template_name = 'producto_pedido_delete.html'
    success_url = reverse_lazy('productos:pedido_list')


class Listado_categorias(ListView):
    model = Categoria
    template_name = 'lista_categorias.html'
    context_object_name = 'categorias'

    def get_queryset(self):
        # Obtener la lista de categorías con la cantidad de artículos por categoría
        from django.db.models import Count
        return Categoria.objects.annotate(num_articulos=Count('producto'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener la lista de categorías con la cantidad de artículos por categoría
        context['categorias'] = self.get_queryset()
        return context

class ProductosPorCategoriaView(ListView):
    model = Producto
    template_name = 'productos_por_categoria.html'
    context_object_name = 'productos'

    def get_queryset(self):
        categoria_id = self.kwargs['categoria_id']
        return Producto.objects.filter(categoria__id=categoria_id)

class ProductoFilterView(FilterView):
    filterset_class = ProductoFilter
    template_name = 'producto_filtro_list.html'
    queryset = Producto.objects.all()

base_inventario/productos/templates/CRUD_pedido.html
{% extends 'index_inventario.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container col-md-10">
  <div class="card bg-dark text-white">
    <div class="card-body">
      <h4 class="card-title border-primary">Pedido</h4>
      <p class="card-text text-center col-md-10 offset-1">Compra de artículos</p>
      <form method="post" class="offset-md-1">
        {% csrf_token %}
        {{ form }}

        <div class="mt-3">
          <button class="btn btn-primary offset-10" type="submit">PEDIR</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

base_inventario/productos/templates/detalles_productos.html
{% extends 'index_productos.html' %}
{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<div class="container">
    <div class="card border-primary col-md-8 offset-md-1 fondo">
        <div class="card-header">
            <h4 class="card-title">Articulo Nuevo</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre Articulo</label>
                    <input name="nombre" type="text" value="{{object.nombre}}" class="form-control" id="nombre" disabled>
                </div>

                <div class="mb-3">
                    <label for="descripcion" class="form-label">Detalles del Articulo</label>
                    <input name="descripcion" type="text" value="{{object.descripcion}}" class="form-control" id="descripcion" disabled>
                </div>

                <div class="mb-3">
                    <label for="marca" class="form-label">Marca</label>
                    <input name="marca" type="text" value="{{object.marca}}" class="form-control" id="marca" disabled>
                </div>

                <div class="mb-3">
                    <label for="precio_unitario" class="form-label">Precio Unitario</label>
                    <input name="precio_unitario" type="text" value="{{object.precio_unitario}}" class="form-control" id="precio_unitario" disabled>
                </div>

                <div class="mb-3">
                    <label for="inventario" class="form-label">Inventario actual</label>
                    <input name="inventario" type="number" value="{{object.inventario}}" class="form-control" id="inventario" disabled>
                </div>

                <div class="mb-3">
                    <label for="factor_de_empaque" class="form-label">Factor de empaque</label>
                    <input name="factor_de_empaque" type="text" value="{{object.factor_de_empaque}}" class="form-control" id="factor_de_empaque" disabled>
                </div>

                <div class="mb-3">
                    <label for="empresa_proveedor" class="form-label">Empresa Proveedor</label>
                    <input name="empresa_proveedor" type="text" value="{{object.empresa_proveedor}}" class="form-control" id="empresa_proveedor" disabled>
                </div>

                <div class="mb-3">
                    <label for="categoria" class="form-label">Categoria</label>
                    <input name="categoria" type="text" value="{% for categoria in producto.categoria.all %}| {{ categoria }}|{% endfor %}" class="form-control" id="categoria" disabled>
                </div>

                <div class="mt-3">
                    <a class="btn btn-info" href="{% url 'productos:productos_listar' %}">Ir a catalogo de productos</a>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    .card-footer,
    .card-header {
        border-radius: 10px;
    }
</style>
{% endblock content %}

base_inventario/productos/templates/index_inventario.html
{% extends 'index_productos.html' %}
{% load static %}

{% block title %}Inventario{% endblock %}

{% block side_bar %}
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <ul class="nav flex-column">
        <h3 class="container">Stock Mercadería</h3>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:pedido_nuevo' %}">Realizar Pedidos</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:categorias_list' %}">Categorias</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:pedido_list' %}">Ver Pedido</a>
        </li>
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <h4 class="display-4">Consulta de Inventario</h4>
    <p class="lead">Cómo puedes encontrar nuestro manual de usuario.</p>
    <hr class="my-4">
    <p class="lead">Si estás logeado, recuerda cerrar sesión al terminar tu trabajo.</p>
    <p class="lead">
        <a class="btn btn-secondary btn-sm" href="#" role="button">Leer más...</a>
    </p>
</div>
<style>
    .jumbotron {
        border-radius: 10px;
    }
</style>
{% endblock content %}

base_inventario/productos/templates/index_productos.html
{% extends 'base/base_menu.html' %}

{% block title %}Productos{% endblock %}

{% block side_bar %}
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <ul class="nav flex-column">
        <h3 class="container">Mercadería</h3>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:productos_listar' %}">Lista de Articulos</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:buscar_producto' %}">Buscar por ID/Categoría</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:productos_nuevo' %}">Crear artículo</a>
        </li>
    </ul>
</div>
{% endblock side_bar %}

{% block content %}
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <h4 class="display-4">Consulta de Productos</h4>
    <p class="lead">Cómo puedes encontrar nuestro manual de usuario.</p>
    <hr class="my-4">
    <p class="lead">Si estás logeado, recuerda cerrar sesión al terminar tu trabajo.</p>
    <br>
    <p class="lead">
        <a class="btn btn-secondary btn-sm" href="#" role="button">Leer más...</a>
    </p>
</div>

{% endblock content %}

base_inventario/productos/templates/lista_categorias.html
{% extends 'index_inventario.html' %}

{% block content %}
<div class="row">
    <table class="table table-dark table-hover table-responsive col-md-8 mt-3">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nombre</th>
                <th>Stock</th>
            </tr>
        </thead>
        <tbody>
            {% if categorias %}
                {% for categoria in categorias %}
                    <tr>
                        <td>{{ categoria.id }}</td>
                        <td><a class="btn btn-dark" href="{% url 'productos:productos_por_categoria' categoria.id %}">{{ categoria.nombre }}</a></td>
                        <td>{{ categoria.num_articulos }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">No hay categorías registradas</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock content %}

base_inventario/productos/templates/lista_productos.html
{% extends 'index_productos.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <input type="text" id="searchInput" class="form-control" placeholder="Buscar artículos...">
        </div>
    </div>
</div>

<div class="row">
    <table class="table table-dark table-hover table-responsive mt-3" id="productosTable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Precio/Unidad</th>
                <th>Stock</th>
                <th>Categorías</th>
                <th>Editar</th>
                <th>Eliminar</th>
                <th>Ver detalles</th>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for producto in object_list %}
            <tr>
                <td>{{ producto.id }}</td>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.marca }}</td>
                <td>{{ producto.precio_unitario }}</td>
                <td>{{ producto.inventario }}</td>
                <td>
                    {% for categoria in producto.categoria.all %}
                    |{{ categoria }}|
                    {% endfor %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'productos:productos_editar' producto.id %}">Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger" href="{% url 'productos:productos_eliminar' producto.id %}">Eliminar</a>
                </td>
                <td>
                    <a class="btn btn-info" href="{% url 'productos:productos_detail' producto.id %}">Detalles</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="10">No hay productos disponibles en el catálogo</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<div class="container">
    <a class="btn btn-success" href="{% url 'productos:productos_nuevo' %}">Nuevo Producto</a>
</div>

<script type="text/javascript">
    // Función para realizar la búsqueda de artículos
    function buscarArticulos() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("productosTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1]; // Columna de Nombre
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    document.getElementById("searchInput").addEventListener("input", buscarArticulos);
</script>

{% endblock content %}

base_inventario/productos/templates/pedido_reporte.html
{% extends 'index_inventario.html' %}

{% block content %}
<div class="container">
    <table class="table table-dark table-hover table-responsive col-md-8 mt-3">
        <thead>
            <tr>
                <th>Código</th>
                <th>Producto</th>
                <th>Fecha de Pedido</th>
                <th>Unidades Pedidas</th>
                <th>Opción 1</th>
                <th>Opción 2</th>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for pedido in object_list %}
            <tr class="text-center">
                <td>{{ pedido.producto_a_pedir.id }}</td>
                <td>{{ pedido.producto_a_pedir }}</td>
                <td>{{ pedido.fecha_compra }}</td>
                <td>{{ pedido.cantidad }}</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="{% url 'productos:pedido_edit' pedido.id %}">Editar</a>
                </td>
                <td>
                    <a class="btn btn-danger btn-sm" href="{% url 'productos:pedido_delete_producto' pedido.id %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="6">No hay ningún producto en pedidos.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <div class="col-md-9 offset-8">
        <a class="btn btn-success" href="{% url 'productos:pedido_nuevo' %}">Nuevo Producto</a>
        <a class="btn btn-primary" href="{% url 'pedido_pdf' %}">Generar Reporte</a>
    </div>
</div>
{% endblock content %}

base_inventario/productos/templates/producto_filtro_list.html
{% extends 'index_productos.html' %}
{% load static %}

{% block content %}
<div class="container col-md-10 bg-dark p-3 border rounded border-3 border-white mt-3 text-white mb-3">
    <div class="bg-dark text-white">
        <div class="card-header text-center p-3">
            <h4 class="text-white">Buscar Artículos</h4>
        </div>
        <form method="GET" class="p-3">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-control">
                        <h6 id="helpId" class="form-text text-black">Selecciona la categoría</h6>
                        {{ filter.form.categoria}}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <p>{{ filter.form.id}}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-secondary btn-sm mt-3">Buscar</button>                    
                </div>
            </div>
        </form>
    </div>

    <div class="table-responsive mt-1">
        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th class="col-2">ID</th>
                    <th class="col-8 text-center">Artículo</th>
                    <th class="col-2">STOCK</th>
                </tr>
            </thead>
        </table>
    </div> 

    {% if object_list %}
    {% for producto in filter.qs %}
    <div class="table-responsive mt-3">
        <table class="table table-dark">
            <tbody>
                <tr>
                    <td class="col-2">{{ producto.id }}</td>
                    <td class="col-8 text-center">{{ producto.nombre }}</td>
                    <td class="col-2">{{ producto.inventario }}</td>
                </tr>
            </tbody>
        </table>
    </div>    
    {% endfor %}
    {% else %}
    <div class="mt-3">
        <div class="card card-dark">
            <div class="card-body">
                <ul class="list-group">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-center text-white">No hay resultados que mostrar</h5>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

base_inventario/productos/templates/producto_pedido_delete.html
{% extends 'base/base_menu.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3 offset-md-5">
            <form method="post">
                {% csrf_token %}
                <h2>¿Desea eliminar el registro {{ object.producto_a_pedir }} de la lista de pedido?</h2>
                <button class="btn btn-danger botones" type="submit">Si</button>
                <a class="btn btn-secondary botones" href="{% url 'productos:pedido_list' %}">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

base_inventario/productos/templates/productos_delete.html
{% extends 'base/base_menu.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <style>
            .delete {
                background-color: #C6E3F6;
                border-radius: 5px;
                padding: 5px;
                box-shadow: 5px 5px 5px #AFACAD;
            }
        </style>

        <div class="col-md-5">
            <div class="delete">
                <form method="post">
                    {% csrf_token %}
                    <h2>¿Desea eliminar el registro {{ producto.nombre }} de la lista de pedido?</h2>
                    <button class="btn btn-danger botones" type="submit">Si</button>
                    <a class="btn btn-secondary botones" href="{% url 'productos:pedido_list' %}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

base_inventario/productos/templates/productos_form.html
{% extends 'index_productos.html' %}

{% block content %}
<div class="container col-md-10 mt-3 ">
    <div id="formularios" >
        <div class="card bg-dark text-white">
            <div class="card-header bg-dark text-white">
                <h3 class="text-center">Crear Articulo</h3>
            </div>
            <form method="post" class="card-body bg-dark text-white">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre Articulo</label>
                            <input name="nombre" type="text" value="{{ object.nombre }}" class="form-control" id="nombre" required>
                        </div>
        
                        <div class="mb-3">
                            <label for="descripcion" class="form-label">Descripcion</label>
                            {{ form.descripcion }}
                        </div>
        
                        <div class="mb-3">
                            <label for="marca" class="form-label">Marca</label>
                            <input name="marca" type="text" value="{{ object.marca }}" class="form-control" id="marca" required>
                        </div>
                    </div>
    
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="precio_unitario" class="form-label">Precio Unitario</label>
                            <input name="precio_unitario" type="text" value="{{ object.precio_unitario }}" class="form-control" id="precio_unitario" required>
                        </div>
        
                        <div class="mb-3">
                            <label for="inventario" class="form-label">Stock inicial</label>
                            <input name="inventario" type="number" value="{{ object.inventario }}" class="form-control" id="inventario">
                        </div>
        
                        <div class="mb-3">
                            <label for="factor_de_empaque" class="form-label">Factor de empaque</label>
                            <select name="factor_de_empaque" class="form-select" id="factor_de_empaque">
                                <option type="select" {{ form.factor_de_empaque }}
                            </select>
                        </div>
        
                        <div class="mb-3">
                            <label for="empresa_proveedor" class="form-label">Empresa</label>
                            <select name="empresa_proveedor" class="form-select" id="empresa_proveedor">
                                <option type="select" {{ form.empresa_proveedor }}
                            </select>
                        </div>
        
                        <div class="mb-3">
                            <label for="categoria" class="form-label">Categoría</label>
                            <p>{% for categoria in form.categoria %}<br>{{ categoria }}{% endfor %}</p>
                        </div>
        
                        <p class="help-block">Antes de guardar la información asegúrese de que los datos son correctos.</p>
        
                        <button type="submit" class="btn btn-primary btn-block botones">Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
{% endblock content %}