base_inventario/base_inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from .views import PedidoPDF, EmpresasPDF, PerfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('productos/', include('productos.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido_pdf/', login_required(PedidoPDF.as_view()), name='pedido_pdf'),
    path('empresas_pdf/', login_required(EmpresasPDF.as_view()), name='empresas_pdf'),
    path('perfiles_pdf/', login_required(PerfilPDF.as_view()), name='perfiles_pdf'),
]

base_inventario/perfil/urls.py
from django.urls import path
from .views import RegistroUsuario, empresas_index, Usuario_ListView, proveedores_list, Listado_empresas, Crear_empresa, Editar_empresa, Eliminar_empresa, PerfilCrear, index_perfiles
from django.contrib.auth.decorators import login_required

app_name = 'perfil'
urlpatterns = [
    path('index_perfiles/', index_perfiles, name='index_perfiles'),
    path('crear', login_required(RegistroUsuario.as_view()), name='crear'),
    path('usuario_list', Usuario_ListView.as_view(), name='usuario_list'),
    path('empresas_index', empresas_index, name='empresas_index'),
    path('empresa', Crear_empresa.as_view(), name='empresa'),
    path('empresas_list', Listado_empresas.as_view(), name='empresas_list'),
    path('editar/<int:pk>/', Editar_empresa.as_view(), name='empresas_edit'),
    path('eliminar/<int:pk>/', Eliminar_empresa.as_view(), name='empresas_delete'),
    path('proveedores_crear', PerfilCrear.as_view(), name='proveedores_crear'),
    path('proveedores_list', proveedores_list, name='proveedores_list'),
]

base_inventario/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from productos.views import (
    index_productos, Listado_producto, Editar_producto, Borrar_producto,
    Listado_pedido, Editar_pedido, Borrar_producto_pedido, Listado_categorias,
    inventario_view, Crear_producto, Detalles_producto, Crear_pedido, ProductosPorCategoriaView)

from django_filters.views import FilterView
from .filters import ProductoFilter

app_name = 'productos'

urlpatterns = [
    path('index', login_required(index_productos), name='index_productos'),
    path('nuevo', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    path('pedido', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
    path('listar', login_required(Listado_producto.as_view()), name='productos_listar'),
    re_path(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
    re_path(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
    path('buscar_producto', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='producto_filtro_list.html')), name='buscar_producto'),
    re_path(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
    re_path(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
    re_path(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()), name='pedido_edit'),
    path('pedido_list', login_required(Listado_pedido.as_view()), name='pedido_list'),
    path('categorias_list', login_required(Listado_categorias.as_view()), name='categorias_list'),
    path('inventario_view', login_required(inventario_view), name='inventario_view'),
    path('buscar_producto_por_empresa', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),
    path('productos/<int:categoria_id>/', ProductosPorCategoriaView.as_view(), name='productos_por_categoria'),


]

base_inventario/perfil/models.py
from django.db import models
from django.contrib.auth.models import User

class EmpresaProveedor(models.Model):
    nombre_empresa = models.CharField(max_length=50, default="")
    nit = models.CharField(max_length=20)
    telefono = models.CharField(max_length=50)
    contacto_email = models.EmailField()

    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"

    def __str__(self):
        return self.nombre_empresa

class Perfil(models.Model):
    empresa_proveedor = models.ForeignKey(EmpresaProveedor, null=True, blank=False, on_delete=models.SET_DEFAULT, default="")
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.TextField(max_length=50, null=True)
    telefono = models.CharField(max_length=50)
    dui = models.CharField(max_length=50, null=True)
    nit = models.CharField(max_length=50, null=True)

    class Meta:
        verbose_name = "Perfil"
        verbose_name_plural = "Perfiles"

    def __str__(self):
        return str(self.usuario)

base_inventario/perfil/forms.py
from django import forms
from .models import Perfil, EmpresaProveedor
from django.contrib.auth.models import User


class PerfilCrear(forms.ModelForm):
    direccion = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 24}))

    class Meta:
        model = Perfil
        fields = ('empresa_proveedor', 'usuario', 'direccion', 'telefono', 'dui', 'nit')
        labels = {
            'usuario': 'Usuario',
            'empresa_proveedor': 'Empresa',
            'direccion': 'Dirección',
            'telefono': 'Teléfono',
            'dui': 'DUI',
            'nit': 'NIT',
        }


class UsuarioCrear(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password')
        labels = {
            'username': 'Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'password': 'Contraseña',
        }

class EmpresaCrear(forms.ModelForm):
    class Meta:
        model = EmpresaProveedor
        fields = ('nombre_empresa', 'nit', 'telefono', 'contacto_email')
        labels = {
            'nombre_empresa': 'Nombre de la Empresa',
            'nit': 'NIT',
            'telefono': 'Teléfono',
            'contacto_email': 'Correo Electrónico',
        }

base_inventario/perfil/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from .forms import PerfilCrear, EmpresaCrear
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import EmpresaProveedor, Perfil


def index_perfiles(request):
    return render(request, 'index_perfil.html')

class RegistroUsuario(CreateView):
    model = User
    template_name = 'CRUD_usuarios.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('perfil:usuario_list')

class Usuario_ListView(ListView):
    model = User
    template_name = 'lista_usuarios.html'

def empresas_index(request):
    return render(request, 'empresas_index.html')

class PerfilCrear(CreateView):
    model = Perfil
    template_name = 'CRUD_Perfiles.html'
    form_class = PerfilCrear
    success_url = reverse_lazy('perfil:proveedores_list')

def proveedores_list(request):
    proveedor = Perfil.objects.all().order_by('id')
    contexto = {'proveedores': proveedor}
    return render(request, 'contactos_proveedores.html', contexto)

class Crear_empresa(SuccessMessageMixin, CreateView):
    model = EmpresaProveedor
    template_name = 'CRUD_empresas.html'
    form_class = EmpresaCrear
    success_url = reverse_lazy('perfil:empresas_list')
    
    def get_success_message(self, cleaned_data):
        return '¡La empresa ha sido registrada con exito!'

class Listado_empresas(ListView):
    model = EmpresaProveedor
    context_object_name = 'empresas'
    ordering = ['id']
    paginate_by = 6
    template_name = 'listado_empresas.html'

class Editar_empresa(UpdateView):
    model = EmpresaProveedor
    template_name = 'CRUD_empresas.html'
    form_class = EmpresaCrear
    success_url = reverse_lazy('perfil:empresas_list')

class Eliminar_empresa(DeleteView):
    model = EmpresaProveedor
    template_name = 'empresa_delete.html'
    success_url = reverse_lazy('perfil:empresas_list')

base_inventario/perfil/templates/CRUD_Perfiles.html
{% extends 'empresas_index.html' %} 

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5 offset-2 mt-3">
            <div id="formularios" class="bg-dark p-3 text-light border rounded border-3 border-dark">
                <form method="post">
                    {% csrf_token %} 
                    <div class="container">
                        <h3 class="text-center">Registro de proveedores</h3>
                        <p>Por favor, rellena este formulario para registrar un proveedor.</p>
                        <hr>

                        <div class="form-group mb-1">
                            <label for="{{ form.usuario.id_for_label }}" class="form-label p-1">Nombre de Usuario:</label>
                            <div class="p-1 col-6">
                                {{ form.usuario }}
                            </div>
                        </div>
                        
                        <div class="form-group mb-1">
                            <label for="{{ form.empresa_proveedor.id_for_label }}" class="form-label">Empresa:</label>
                            <div class="p-1 col-6">
                                {{ form.empresa_proveedor }}
                            </div>
                        </div>
                    
                        <div class="form-group mb-1">
                            <label for="{{ form.direccion.id_for_label }}" class="form-label">Direccion:</label>
                            <div class="p-1 col-6">
                                {{ form.direccion }}
                            </div>
                        </div>    
                        
                        <div class="form-group mb-1">
                            <label for="{{ form.telefono.id_for_label }}" class="form-label">Telefono:</label>
                            <div class="p-1 col-6">
                                {{ form.telefono }}
                            </div>
                        </div>   

                        <div class="form-group mb-1">
                            <label for="{{ form.dui.id_for_label }}" class="form-label">DUI:</label>
                            <div class="p-1 col-6">
                                {{ form.dui }}
                            </div>
                        </div>  

                        <div class="form-group mb-1">
                            <label for="{{ form.nit.id_for_label }}" class="form-label">NIT:</label>
                            <div class="p-1 col-6">
                                {{ form.nit }}
                            </div>
                        </div>  
                        <hr>
                        <button type="submit" class="btn btn-secondary btn-block botones">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

base_inventario/perfil/templates/CRUD_empresas.html
{% extends 'empresas_index.html' %} 

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5 offset-2 mt-3">
            <div id="formularios" class="bg-dark p-3 text-light border rounded border-3 border-dark">
                <form method="post">
                    {% csrf_token %} 
                    <div class="container">
                        <h3 class="text-center">Registro de Empresas</h3>
                        <p>Por favor, rellena este formulario para registrar una empresa</p>
                        <hr>

                        <div class="form-group mb-1">
                            <label for="{{ form.nombre_empresa.id_for_label }}" class="form-label p-1">Nombre Empresa:</label>
                            <div class="p-1 col-6">
                                {{ form.nombre_empresa }}
                            </div>
                        </div>
                        
                        <div class="form-group mb-1">
                            <label for="{{ form.nit.id_for_label }}" class="form-label">NIT:</label>
                            <div class="p-1 col-6">
                                {{ form.nit }}
                            </div>
                        </div>
                    
                        <div class="form-group mb-1">
                            <label for="{{ form.telefono.id_for_label }}" class="form-label">Telefono:</label>
                            <div class="p-1 col-6">
                                {{ form.telefono }}
                            </div>
                        </div>    
                        
                        <div class="form-group mb-1">
                            <label for="{{ form.contacto_email.id_for_label }}" class="form-label">Email:</label>
                            <div class="p-1 col-6">
                                {{ form.contacto_email }}
                            </div>
                        </div>   

                        <hr>
                        

                        <button type="submit" class="btn btn-secondary btn-block botones">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

base_inventario/perfil/templates/CRUD_usuarios.html
{% extends 'index_perfil.html' %} 

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5 offset-2 mt-3">
            <div id="formularios" class="bg-dark p-3 text-light border rounded border-3 border-dark">
                <form method="post">
                    {% csrf_token %} 
                    <div class="container">
                        <h3 class="text-center">Registro de Usuario</h3>
                        <p>Por favor, rellena este formulario para crear una cuenta de usuario.</p>
                        <hr>

                        <div class="form-group mb-1">
                            <label for="{{ form.username.id_for_label }}" class="form-label p-1">Usuario:</label>
                            <div class="p-1 col-6">
                                {{ form.username }}
                            </div>
                        </div>
                        
                        <div class="form-group mb-1">
                            <label for="{{ form.password1.id_for_label }}" class="form-label">Contraseña:</label>
                            <div class="p-1 col-6">
                                {{ form.password1 }}
                            </div>
                        </div>
                    
                        <div class="form-group mb-1">
                            <label for="{{ form.password2.id_for_label }}" class="form-label">Confirmar contraseña:</label>
                            <div class="p-1 col-6">
                                {{ form.password2 }}
                            </div>
                        </div>     

                        <hr>
                        <p>Al crear una cuenta, usted acepta nuestros <a href="#">Términos y condiciones</a>.</p>

                        <button type="submit" class="btn btn-secondary btn-block botones">Registrar usuario</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

base_inventario/perfil/templates/contactos_proveedores.html
{% extends 'empresas_index.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
            <div class="jumbotron">
                <h3 class="display-5">Consulta de contactos de proveedores</h3>
                <br>
                <table class="table table-dark table-hover table-responsive col-md-8 mt-3 text-light">
                    <thead>
                        <tr>
                            <th>Id</th>
                            
                            <th>Usuario</th>
                            <th>Empresa</th>
                            <th>NIT</th>
                            <th>Telefono</th>
                            <th>Direccion</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% if proveedores %}
                        {% for proveedor in proveedores %}
                        <tr>
                            <td>{{ proveedor.id }}</td>
                            <td>{{ proveedor.usuario.username }}</td>
                            <td>{{ proveedor.empresa_proveedor.nombre_empresa }}</td>
                            <td>{{ proveedor.nit }}</td>
                            <td>{{ proveedor.telefono }}</td>
                            <td>{{ proveedor.direccion }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="8" class="text-center display-6">
                                No existen proveedores registrados.
                            </td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div class="container">
                    <a class="btn btn-primary" href="{% url 'perfiles_pdf' %}">Reporte de proveedores</a>
                    <a class="btn btn-success" href="{% url 'perfil:proveedores_crear' %}">Registrar un proveedor</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

base_inventario/perfil/templates/empresa_delete.html
{% extends 'empresas_index.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5 offset-2">
            <div class="delete">
                <form method="post">
                    {% csrf_token %} {# token de seguridad #}
                    <h2><p class="help-block"></p>¿Desea eliminar el registro {{ object.nombre_empresa }} de la base de datos?</p></h2>
                    <button class="btn btn-danger botones" type="submit">Sí</button>
                    <a class="btn btn-default" href="{% url 'perfil:empresas_list' %}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

base_inventario/perfil/templates/empresas_index.html
{% extends 'base/base_menu.html' %}
{% load static %}

{% block title %}Empresas{% endblock %}

{% block side_bar %} 
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <ul class="nav flex-column">
        <h3 class="container">Empresas</h3>
        
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'perfil:empresas_list' %}">Listado de Empresas</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'perfil:empresa' %}">Registrar Empresa</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'perfil:proveedores_list' %}">Contacto de Proveedores</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'productos:buscar_producto_por_empresa' %}">Stock por empresa</a>
        </li>
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="container bg-dark p-3 border rounded border-3 border-dark text-light">
        <h4 class="display-4">Consulta de empresas y contactos!</h4>
        <p class="lead">Cómo puedes encontrar nuestro manual de usuario.</p>
        <hr class="my-4">
        <p class="lead">Si estás logeado, recuerda cerrar sesión al terminar tu trabajo.</p>
        <br>
        <p class="lead">
            <a class="btn btn-secondary" href="#" role="button">Leer más...</a>
        </p>
    </div>
</div>
</style>
{% endblock content %}

base_inventario/perfil/templates/index_perfil.html
{% extends 'base/base_menu.html' %}
{% load static %}

{% block title %}Usuarios{% endblock %}

{% block side_bar %}
<div class="container bg-dark p-3 border rounded border-3 border-dark mt-3 text-white">
    <ul class="nav flex-column">
        <h3 class="container">Usuarios</h3>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'perfil:crear' %}">Crear Usuario</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-dark" href="{% url 'perfil:usuario_list' %}">Lista de Usuarios</a>
        </li>
    </ul>
</div>

{% endblock %}

{% block content %}
    <div class="container bg-dark p-3 border rounded border-3 border-dark text-light">
        <h4 class="display-4">Consulta de Usuarios</h4>
        <p class="">Cómo puedes encontrar nuestro manual de usuario.</p>
        <p class="">Si estás logeado, recuerda cerrar sesión al terminar tu trabajo.</p>
        <br>
        <p class="lead">
            <a class="btn btn-secondary btn-sm" href="#" role="button">Leer más...</a>
        </p>
    </div>
{% endblock content %}

base_inventario/perfil/templates/lista_usuarios.html
{% extends 'index_perfil.html' %}
{% load static %}

{% block content %}
  {% block extraheader %}
  {% endblock extraheader %}

  <div class="container">
    <table class="table table-dark table-hover table-responsive col-md-8 mt-3">
      <thead>
        <tr>
          <th>Id</th>
          <th>Usuario</th>
          <th>Fecha de Creación</th>
          <th>Última Fecha de Ingreso</th>
        </tr>
      </thead>
      <tbody>
        {% if object_list %}
        {% for usuario in object_list %}
        <tr>
          <td>{{ usuario.id }}</td>
          <td>{{ usuario.username }}</td>
          <td>{{ usuario.date_joined }}</td>
          <td>{{ usuario.last_login }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
          <td colspan="4">
            <h1>No hay ningún Usuario Registrado</h1>
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
    
    <div class="">
      <a class="btn btn-secondary" href="{% url 'perfil:crear' %}">Crear un usuario</a>
    </div>
  </div>
{% endblock content %}

base_inventario/perfil/templates/listado_empresas.html
{% extends 'empresas_index.html' %}

{% block content %}
  <div class="container ">
    <table class="table table-dark table-hover table-responsive col-md-8 mt-3 text-light">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>NIT</th>
          <th>Telefono</th>
          <th>Email</th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        {% if object_list %}
          {% for empresa in object_list %}
            <tr>
              <td>{{ empresa.id }}</td>
              <td>{{ empresa.nombre_empresa|upper }}</td>
              <td>{{ empresa.nit }}</td>
              <td>{{ empresa.telefono }}</td>
              <td>{{ empresa.contacto_email }}</td>
              <td>
                <a class="btn btn-primary btn-sm" href="{% url 'perfil:empresas_edit' empresa.id %}">Editar</a>
              </td>
              <td>
                <a class="btn btn-danger btn-sm" href="{% url 'perfil:empresas_delete' empresa.id %}">Eliminar</a>
              </td>
            </tr>
          
          {% endfor %}
        {% else %}
          <div class="container bg-dark p-3 border rounded border-3 border-dark text-light">
            <div class="jumbotron jumbotron-fluid">
              <div class="container">
                <h3 class="display-4">No hay empresas registradas</h3>
                <p class="lead">¿Desea agregar una empresa?</p>
                <hr class="my-2">
                <p class="lead">
                  <a class="btn btn-secondary" href="{% url 'perfil:empresa' %}" role="button">Agregar</a>
                </p>
              </div>
            </div>
          </div>
        {% endif %}     
      </tbody>
    </table>
    <div class="container">
      <a class="btn btn-secondary" href="{% url 'perfil:empresa' %}" role="button">Registrar empresa</a>
      <a class="btn btn-primary" href="{% url 'empresas_pdf' %}">Generar Reporte</a>
    </div>
    {% if is_paginated %}
      <div class="col-md-3 offset-4">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">ANTERIOR</a></li>
            {% else %}
              <li class="disabled page-item"><span class="page-link">ANTERIOR</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a class="page-link" href="?page={{ page_obj.next_page_number }}">SIGUIENTE</a></li>
            {% else %}
              <li class="disabled page-item"><span class="page-link">SIGUIENTE</span></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    {% endif %}
  </div>
{% endblock content %}