base_inventario/base_inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from .views import PedidoPDF, EmpresasPDF, PerfilPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('productos/', include('productos.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido_pdf/', login_required(PedidoPDF.as_view()), name='pedido_pdf'),
    path('empresas_pdf/', login_required(EmpresasPDF.as_view()), name='empresas_pdf'),
    path('perfiles_pdf/', login_required(PerfilPDF.as_view()), name='perfiles_pdf'),
]

base_inventario/perfil/urls.py
from django.urls import path
from .views import RegistroUsuario, empresas_index, Usuario_ListView, proveedores_list, Listado_empresas, Crear_empresa, Editar_empresa, Eliminar_empresa, PerfilCrear, index_perfiles
from django.contrib.auth.decorators import login_required

app_name = 'perfil'
urlpatterns = [
    path('index_perfiles/', index_perfiles, name='index_perfiles'),
    path('crear', login_required(RegistroUsuario.as_view()), name='crear'),
    path('usuario_list', Usuario_ListView.as_view(), name='usuario_list'),
    path('empresas_index', empresas_index, name='empresas_index'),
    path('empresa', Crear_empresa.as_view(), name='empresa'),
    path('empresas_list', Listado_empresas.as_view(), name='empresas_list'),
    path('editar/<int:pk>/', Editar_empresa.as_view(), name='empresas_edit'),
    path('eliminar/<int:pk>/', Eliminar_empresa.as_view(), name='empresas_delete'),
    path('proveedores_crear', PerfilCrear.as_view(), name='proveedores_crear'),
    path('proveedores_list', proveedores_list, name='proveedores_list'),
]

base_inventario/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from productos.views import (
    index_productos, Listado_producto, Editar_producto, Borrar_producto,
    Listado_pedido, Editar_pedido, Borrar_producto_pedido, Listado_categorias,
    inventario_view, Crear_producto, Detalles_producto, Crear_pedido, ProductosPorCategoriaView)

from django_filters.views import FilterView
from .filters import ProductoFilter

app_name = 'productos'

urlpatterns = [
    path('index', login_required(index_productos), name='index_productos'),
    path('nuevo', login_required(Crear_producto.as_view()), name='productos_nuevo'),
    path('pedido', login_required(Crear_pedido.as_view()), name='pedido_nuevo'),
    path('listar', login_required(Listado_producto.as_view()), name='productos_listar'),
    re_path(r'^editar/(?P<pk>\d+)/$', login_required(Editar_producto.as_view()), name='productos_editar'),
    re_path(r'^productos_detail/(?P<pk>\d+)/$', login_required(Detalles_producto.as_view()), name='productos_detail'),
    path('buscar_producto', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='producto_filtro_list.html')), name='buscar_producto'),
    re_path(r'^eliminar/(?P<pk>\d+)/$', login_required(Borrar_producto.as_view()), name='productos_eliminar'),
    re_path(r'^pedido_delete_producto/(?P<pk>\d+)/$', login_required(Borrar_producto_pedido.as_view()), name='pedido_delete_producto'),
    re_path(r'^pedido_edit/(?P<pk>\d+)/$', login_required(Editar_pedido.as_view()), name='pedido_edit'),
    path('pedido_list', login_required(Listado_pedido.as_view()), name='pedido_list'),
    path('categorias_list', login_required(Listado_categorias.as_view()), name='categorias_list'),
    path('inventario_view', login_required(inventario_view), name='inventario_view'),
    path('buscar_producto_por_empresa', login_required(FilterView.as_view(filterset_class=ProductoFilter, template_name='stock_por_empresa_filtro_list.html')), name='buscar_producto_por_empresa'),
    path('productos/<int:categoria_id>/', ProductosPorCategoriaView.as_view(), name='productos_por_categoria'),


]

base_inventario/templates/base/base.html
{% extends 'base/base_menu.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block extrahead %}
    
    {% endblock extrahead %}
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar_login.css' %}">

</head>
<body>
    {% block header %}
    
    {% endblock header %}
    {% block nav_bar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'home' %}"><strong> Sistema de Inventarios</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
       
    </nav>
    <br>
    <br>
    <br>
    {% endblock nav_bar%}

    {% block content %}
    
    {% endblock content %}
</body>
{% block footer %} 
    
{% endblock footer %}
</html>

base_inventario/templates/base/base_menu.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <title>
        {% block title %}Inventario de mercadería{% endblock %}
    </title>
</head>
<body>
{% block header %}{% endblock %}

{% block nav_bar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top mb-5">
    <a class="navbar-brand" href="{% url 'home' %}"><strong>Sistema de Inventarios</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:empresas_index' %}"><strong>Empresas</strong><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:index_productos' %}"><strong>Mercadería</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:inventario_view' %}"><strong>Control de Inventarios</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:index_perfiles' %}"><strong>Usuarios</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}"><strong>Salir</strong></a>
            </li>
        </ul>
        {% comment %} <form class="d-flex">
            <input class="form-control me-2" type="search" name="busqueda" placeholder="Buscar por palabra" required>
            <button class="btn btn-secondary" type="submit">BUSCAR</button>
        </form> {% endcomment %}
    </div>
</nav>
{% endblock nav_bar %}
<br><br><br>

{% if messages %}
    {% for message in messages %}
        <div id="msg" class="alert alert-info">
            {{ message }}
            <br>
        </div>
    {% endfor %}
{% endif %}
<script>
    setTimeout(function () {
        document.querySelector('#msg').remove();
    }, 3000);
</script>


<div class="row">
    <div class="col-md-2">
        {% block side_bar %}
        {% endblock side_bar %}
    </div>

    <div class="col-md-6 offset-1">
        {% block content %}
        {% endblock content %}
    </div>
</div>

<br><br><br>

{% block footer %}
<div id="footer" class="row fixed-bottom bg-dark text-center ">    
    <p class="p-2">
        <h6 class="text-white">Creado por: Julio Dominguez</h6>
    </p>
</div>



{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>